### PR TITLE
2 minor fixes

### PR DESCRIPTION
**Pull request by andrey012**
Hello, 

1. I've removed openCloseDir handler on file items in file list (this handler is not applicable for files anyway). 
2. I've added some lines of code to preserve existing lineendings of existing files when overwriting them. 
3. when Ctrl-F - select text in find text input in order to make user able to enter new text right away, without need to remove old text first

### CODE REVIEW

**Comment by mattpass** [comment]
Thanks for this - just need to go thru updates before I pull in but looking good so far. (Mainly need to check point no.1 as file/dir items are created in a couple of other places in the main JS file also).

**Comment by mattpass** [comment]
@andrey012 This looks like a set of really good improvements - thanks. Going to go through them now and then pull in and get back to you on anything I'm not sure of/could be problematic.

**Comment by andrey012** [comment]
> but what was the issue re double click problem. Is the problem that double click wasn't firing every time?

As I remember on one of my *pads I could not doubleclick on file, because it first fired single click event and the events messed somehow. I'm not sure - it was quite long ago. Anyway - I thougth, that the less events there are - the better, and since we do not handle singleclick event for files anyway - why not to remove it completely.

**Comment by andrey012** [comment]
There are quite a lot of commits around improving of handling file+line format. I found, that it is quite useful if you can copy a line containing filename+linenumber from log stack trace, and then Ctrl-O Ctrl-V Enter - and get directly to the exact line. 
But all the logs contain this file+line in different way - some show "file:line", others "file line 123", others "file on line 123" and so on. 
So now I'm adding a branch for each case to make it work everywhere. If you think this feature should be configurable - please let me know, I'll add configuration switch.

**Comment by andrey012** [comment]
> Does this really work? If so, ace!! :-D (Did you test this, or is it just 'probably' will work?)
Yes, I have hardly tested it, because I make changes on numerous projects and we do not have strict line ending policy - so all of files may have different line endings. Luckily there are rarely files, that have mix of line endings within one file :). 

This fix helped me a lot - otherwise e.g. Git diff will basically report, that whole file have changed.

**Comment by mattpass** [comment]
Yeah, apologies for not getting back to you sooner - have been busy on a few things recently and this PR was bigger than I expected (deceptively named '2 minor fixes') ;-)

There's so much awesomeness here - thank you so much! Some annoying bugs fixed and some very cool new features.

Couple of things tho:
1. We do actually handle single click events for files - they open files on mobile devices where double clicks aren't well supported (eg phone).
2. Re the open and go to file thing and see your thought on the 3 formatting cases. A great idea! :-)

OK, what I'm going to do is pull this in and maybe apply a few tweaks/additions ontop (nothing major, the biggest thing being your changes to the file/folder ondrag thing - need to replicate this in ice-coder.js also where it generates LI nodes on adding new items to the file manager).

Once again - thank you loads for these updates! :+1:

**Pull request merged**
